/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootSpaRouteImport } from './routes/__root.spa'
import { Route as SklIjazahRouteImport } from './routes/skl-ijazah'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as ScanningRouteImport } from './routes/scanning'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PraktekRouteImport } from './routes/praktek'
import { Route as UjianTertulisRouteImport } from './routes/ujian-tertulis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KurmerRouteImport } from './routes/kurmer'
import { Route as IdentitasRouteImport } from './routes/identitas'
import { Route as HasilUjianRouteImport } from './routes/hasil-ujian'
import { Route as HasilAkhirRouteImport } from './routes/hasil-akhir'
import { Route as ExcelToolsRouteImport } from './routes/excel-tools'
import { Route as DaftarMadrasahRouteImport } from './routes/daftar-madrasah'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const _rootSpaRoute = _rootSpaRouteImport.update({
  id: '/__root/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const SklIjazahRoute = SklIjazahRouteImport.update({
  id: '/skl-ijazah',
  path: '/skl-ijazah',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanningRoute = ScanningRouteImport.update({
  id: '/scanning',
  path: '/scanning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktekRoute = PraktekRouteImport.update({
  id: '/praktek',
  path: '/praktek',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianTertulisRoute = UjianTertulisRouteImport.update({
  id: '/ujian-tertulis',
  path: '/ujian-tertulis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KurmerRoute = KurmerRouteImport.update({
  id: '/kurmer',
  path: '/kurmer',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitasRoute = IdentitasRouteImport.update({
  id: '/identitas',
  path: '/identitas',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilUjianRoute = HasilUjianRouteImport.update({
  id: '/hasil-ujian',
  path: '/hasil-ujian',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilAkhirRoute = HasilAkhirRouteImport.update({
  id: '/hasil-akhir',
  path: '/hasil-akhir',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelToolsRoute = ExcelToolsRouteImport.update({
  id: '/excel-tools',
  path: '/excel-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarMadrasahRoute = DaftarMadrasahRouteImport.update({
  id: '/daftar-madrasah',
  path: '/daftar-madrasah',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daftar-madrasah': typeof DaftarMadrasahRoute
  '/excel-tools': typeof ExcelToolsRoute
  '/hasil-akhir': typeof HasilAkhirRoute
  '/hasil-ujian': typeof HasilUjianRoute
  '/identitas': typeof IdentitasRoute
  '/kurmer': typeof KurmerRoute
  '/login': typeof LoginRoute
  '/praktek': typeof PraktekRoute
  '/ujian-tertulis': typeof UjianTertulisRoute
  '/profil': typeof ProfilRoute
  '/scanning': typeof ScanningRoute
  '/siswa': typeof SiswaRoute
  '/skl-ijazah': typeof SklIjazahRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daftar-madrasah': typeof DaftarMadrasahRoute
  '/excel-tools': typeof ExcelToolsRoute
  '/hasil-akhir': typeof HasilAkhirRoute
  '/hasil-ujian': typeof HasilUjianRoute
  '/identitas': typeof IdentitasRoute
  '/kurmer': typeof KurmerRoute
  '/login': typeof LoginRoute
  '/praktek': typeof PraktekRoute
  '/ujian-tertulis': typeof UjianTertulisRoute
  '/profil': typeof ProfilRoute
  '/scanning': typeof ScanningRoute
  '/siswa': typeof SiswaRoute
  '/skl-ijazah': typeof SklIjazahRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daftar-madrasah': typeof DaftarMadrasahRoute
  '/excel-tools': typeof ExcelToolsRoute
  '/hasil-akhir': typeof HasilAkhirRoute
  '/hasil-ujian': typeof HasilUjianRoute
  '/identitas': typeof IdentitasRoute
  '/kurmer': typeof KurmerRoute
  '/login': typeof LoginRoute
  '/praktek': typeof PraktekRoute
  '/ujian-tertulis': typeof UjianTertulisRoute
  '/profil': typeof ProfilRoute
  '/scanning': typeof ScanningRoute
  '/siswa': typeof SiswaRoute
  '/skl-ijazah': typeof SklIjazahRoute
  '/__root/spa': typeof _rootSpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/daftar-madrasah'
    | '/excel-tools'
    | '/hasil-akhir'
    | '/hasil-ujian'
    | '/identitas'
    | '/kurmer'
    | '/login'
    | '/praktek'
    | '/ujian-tertulis'
    | '/profil'
    | '/scanning'
    | '/siswa'
    | '/skl-ijazah'
    | '/spa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/daftar-madrasah'
    | '/excel-tools'
    | '/hasil-akhir'
    | '/hasil-ujian'
    | '/identitas'
    | '/kurmer'
    | '/login'
    | '/praktek'
    | '/ujian-tertulis'
    | '/profil'
    | '/scanning'
    | '/siswa'
    | '/skl-ijazah'
    | '/spa'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/daftar-madrasah'
    | '/excel-tools'
    | '/hasil-akhir'
    | '/hasil-ujian'
    | '/identitas'
    | '/kurmer'
    | '/login'
    | '/praktek'
    | '/ujian-tertulis'
    | '/profil'
    | '/scanning'
    | '/siswa'
    | '/skl-ijazah'
    | '/__root/spa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DaftarMadrasahRoute: typeof DaftarMadrasahRoute
  ExcelToolsRoute: typeof ExcelToolsRoute
  HasilAkhirRoute: typeof HasilAkhirRoute
  HasilUjianRoute: typeof HasilUjianRoute
  IdentitasRoute: typeof IdentitasRoute
  KurmerRoute: typeof KurmerRoute
  LoginRoute: typeof LoginRoute
  PraktekRoute: typeof PraktekRoute
  UjianTertulisRoute: typeof UjianTertulisRoute
  ProfilRoute: typeof ProfilRoute
  ScanningRoute: typeof ScanningRoute
  SiswaRoute: typeof SiswaRoute
  SklIjazahRoute: typeof SklIjazahRoute
  _rootSpaRoute: typeof _rootSpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/spa': {
      id: '/__root/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof _rootSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skl-ijazah': {
      id: '/skl-ijazah'
      path: '/skl-ijazah'
      fullPath: '/skl-ijazah'
      preLoaderRoute: typeof SklIjazahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanning': {
      id: '/scanning'
      path: '/scanning'
      fullPath: '/scanning'
      preLoaderRoute: typeof ScanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktek': {
      id: '/praktek'
      path: '/praktek'
      fullPath: '/praktek'
      preLoaderRoute: typeof PraktekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian-tertulis': {
      id: '/ujian-tertulis'
      path: '/ujian-tertulis'
      fullPath: '/ujian-tertulis'
      preLoaderRoute: typeof UjianTertulisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurmer': {
      id: '/kurmer'
      path: '/kurmer'
      fullPath: '/kurmer'
      preLoaderRoute: typeof KurmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identitas': {
      id: '/identitas'
      path: '/identitas'
      fullPath: '/identitas'
      preLoaderRoute: typeof IdentitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil-ujian': {
      id: '/hasil-ujian'
      path: '/hasil-ujian'
      fullPath: '/hasil-ujian'
      preLoaderRoute: typeof HasilUjianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil-akhir': {
      id: '/hasil-akhir'
      path: '/hasil-akhir'
      fullPath: '/hasil-akhir'
      preLoaderRoute: typeof HasilAkhirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel-tools': {
      id: '/excel-tools'
      path: '/excel-tools'
      fullPath: '/excel-tools'
      preLoaderRoute: typeof ExcelToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-madrasah': {
      id: '/daftar-madrasah'
      path: '/daftar-madrasah'
      fullPath: '/daftar-madrasah'
      preLoaderRoute: typeof DaftarMadrasahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DaftarMadrasahRoute: DaftarMadrasahRoute,
  ExcelToolsRoute: ExcelToolsRoute,
  HasilAkhirRoute: HasilAkhirRoute,
  HasilUjianRoute: HasilUjianRoute,
  IdentitasRoute: IdentitasRoute,
  KurmerRoute: KurmerRoute,
  LoginRoute: LoginRoute,
  PraktekRoute: PraktekRoute,
  UjianTertulisRoute: UjianTertulisRoute,
  ProfilRoute: ProfilRoute,
  ScanningRoute: ScanningRoute,
  SiswaRoute: SiswaRoute,
  SklIjazahRoute: SklIjazahRoute,
  _rootSpaRoute: _rootSpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
